name:                parallel-snake
version:             1.0.0.0
github:              "elc117/t5-2022a-parallel-snake"
author:              "Matheus Machado"
maintainer:          "matheusmazar@gmail.com"
copyright:           "2022 Matheus Machado"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/elc117/t5-2022a-parallel-snake#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random
- containers
- parallel


library:
  source-dirs: src

executables:
  parallel-snake:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parallel-snake
